import { useEffect, useState } from "react";
import axios from "axios";
import { Button, Card, Form, Image, Radio, Slider, Switch, Tabs, Upload, message } from "antd";
import { LayoutOutlined, PictureOutlined, SaveOutlined, UploadOutlined } from "@ant-design/icons";
import { useSettingsStore, type LoginLayoutType, type LoginPageSettings } from "../../store/settings";
import { canAccess, useAuthStore } from "../../store/auth";

const defaults:Record<LoginLayoutType,string>={split:"/iot-login-hero-v2.png",background:"/iot-login-fullscreen-clean.png"};
const errorText=(e:unknown)=>axios.isAxiosError(e)?String(e.response?.data?.error||e.message):"图片上传失败";

export default function SystemSettings(){
 const [form]=Form.useForm<LoginPageSettings>(),{loginPage,loading,saveLoginPage}=useSettingsStore();
 const currentUser=useAuthStore(state=>state.user),canSave=canAccess(currentUser,"system:settings:save");
 const [uploading,setUploading]=useState(false);
 const layout=Form.useWatch("layoutType",form)||loginPage.layoutType,values=Form.useWatch([],form) as LoginPageSettings|undefined;
 const imageField=layout==="split"?"splitImage":"backgroundImage",image=values?.[imageField]||loginPage[imageField]||defaults[layout];
 const opacity=layout==="background"?Number(values?.overlayOpacity??loginPage.overlayOpacity):0;
 useEffect(()=>form.setFieldsValue(loginPage),[form,loginPage]);
 const save=async()=>{try{const next=await form.validateFields();if(!next[imageField])return message.error("请上传当前登录布局使用的图片");await saveLoginPage(next);message.success("系统设置已保存并生效")}catch(e){if(e instanceof Error)message.error("保存系统设置失败")}};
 const upload=async(file:File)=>{const data=new FormData();data.append("file",file);setUploading(true);try{const r=await axios.post("/api/basic-info/upload",data),url=String(r.data?.url||"");if(!url)throw new Error("缺少图片地址");form.setFieldValue(imageField,url);message.success("图片上传成功")}catch(e){message.error(errorText(e))}finally{setUploading(false)}return false};
 const navigation=<Card title="后台导航" className="settings-card settings-tab-card"><Form.Item label="导航布局" name="navigationType" rules={[{required:true,message:"请选择导航布局"}]} extra="保存后立即应用，桌面端可在左侧菜单与顶部菜单之间切换。"><Radio.Group className="navigation-layout-options"><Radio.Button value="sidebar"><LayoutOutlined/> 左侧菜单</Radio.Button><Radio.Button value="top"><LayoutOutlined/> 顶部菜单</Radio.Button></Radio.Group></Form.Item></Card>;
 const imagePicker=<Form.Item required label={layout==="split"?"分栏场景图片":"全屏背景图片"} extra={layout==="split"?"建议使用横向场景图，主体位于左侧或居中。":"建议使用 16:9 高清图，并在右侧为登录表单留白。"}><div className="settings-image-picker"><Image src={image} alt="当前登录页图片" className="settings-image-thumbnail"/><div className="settings-image-meta"><div><PictureOutlined/> 当前使用图片</div><code title={image}>{image}</code>{canSave&&<div className="settings-image-actions"><Upload showUploadList={false} accept="image/jpeg,image/png,image/webp" beforeUpload={upload}><Button icon={<UploadOutlined/>} loading={uploading}>更换图片</Button></Upload><Button onClick={()=>form.setFieldValue(imageField,defaults[layout])}>恢复推荐图片</Button></div>}</div></div></Form.Item>;
 const login=<div className="settings-login-grid"><Card title="登录页设置" className="settings-card settings-login-config"><Form.Item label="登录页类型" name="layoutType" rules={[{required:true,message:"请选择登录页类型"}]}><Radio.Group className="login-layout-options" onChange={e=>{const next=e.target.value as LoginLayoutType,field=next==="split"?"splitImage":"backgroundImage";if(!form.getFieldValue(field))form.setFieldValue(field,defaults[next])}}><Radio.Button value="split"><strong>图文分栏</strong><span>左侧场景图，右侧登录表单</span></Radio.Button><Radio.Button value="background"><strong>全屏背景</strong><span>图片铺满页面，登录表单悬浮</span></Radio.Button></Radio.Group></Form.Item><Form.Item name="splitImage" hidden><input/></Form.Item><Form.Item name="backgroundImage" hidden><input/></Form.Item>{imagePicker}{layout==="background"&&<Form.Item label="背景遮罩颜色深度" name="overlayOpacity" extra="数值越高，背景越暗。"><Slider min={0} max={.8} step={.05} tooltip={{formatter:v=>`${Math.round(Number(v||0)*100)}%`}} marks={{0:"0%",.4:"40%",.8:"80%"}}/></Form.Item>}<Form.Item label="背景动态效果" name="animationEnabled" valuePropName="checked"><Switch checkedChildren="开启" unCheckedChildren="关闭"/></Form.Item></Card><Card title="登录页面预览" className="settings-card settings-preview-panel" extra={layout==="split"?"图文分栏":`全屏背景 · 遮罩 ${Math.round(opacity*100)}%`}><div className={`login-settings-preview preview-${layout}`} style={{backgroundImage:`linear-gradient(rgba(5,24,49,${opacity}),rgba(5,24,49,${opacity})),url("${image}")`}}><div className="login-settings-preview-brand">协议解析工具<small>Protocol Parser Tool</small></div><div className="login-settings-preview-card"><b>欢迎登录</b><span>请输入账号信息进入系统</span><i/><i/><button>登 录</button></div></div><p className="settings-preview-tip">登录页面预览</p></Card></div>;
 return <div className="settings-page settings-page-redesign"><Form form={form} layout="vertical" initialValues={loginPage} className="settings-form settings-form-redesign"><Tabs className="settings-tabs" defaultActiveKey="navigation" items={[{key:"navigation",label:"后台导航",children:navigation},{key:"login",label:"登录页设置",children:login}]}/>{canSave&&<div className="settings-bottom-actions"><Button onClick={()=>form.setFieldsValue(loginPage)}>取消修改</Button><Button type="primary" icon={<SaveOutlined/>} loading={loading} onClick={()=>void save()}>保存设置</Button></div>}</Form></div>
}
