import { useEffect, useRef, useState } from "react";
import axios from "axios";
import * as XLSX from "xlsx";
import { Button, Card, Drawer, Dropdown, Form, Input, Popconfirm, Radio, Select, Space, Tag, message } from "antd";
import { ArrowsAltOutlined, DeleteOutlined, DownloadOutlined, EditOutlined, PlusOutlined, SearchOutlined, ShrinkOutlined, UploadOutlined } from "@ant-design/icons";
import { canAccess, useAuthStore } from "../../store/auth";
import { getErrorMessage } from "../../api/client";
import DataGrid from "../../components/DataGrid";

type Org={id:number;parentId:number;name:string;code:string;status:number;children?:Org[]};
const err=(e:unknown)=>getErrorMessage(e);

export default function OrganizationManagement(){
 const user=useAuthStore(state=>state.user),can=(code:string)=>canAccess(user,code);
 const canQuery=can("basic:organization:query"),canAdd=can("basic:organization:add"),canEdit=can("basic:organization:edit"),canDelete=can("basic:organization:delete"),canImport=can("basic:organization:import"),canTemplate=can("basic:organization:template");
 const [items,setItems]=useState<Org[]>([]),[expanded,setExpanded]=useState<number[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[keyword,setKeyword]=useState(""),[status,setStatus]=useState<number|undefined>();
 const [form]=Form.useForm();const fileRef=useRef<HTMLInputElement>(null);
 const load=async()=>{setLoading(true);try{const response=await axios.get("/api/basic-info/organizations",{params:{page:1,pageSize:200}});const data=response.data.organizations||[];setItems(data);setExpanded(data.map((item:Org)=>item.id))}catch(e){message.error(err(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const openCreate=(parentId=0)=>{form.resetFields();form.setFieldsValue({parentId,status:1});setOpen(true)};
 const save=async()=>{try{const values=await form.validateFields();values.id?await axios.put(`/api/basic-info/organizations/${values.id}`,values):await axios.post("/api/basic-info/organizations",values);message.success("组织机构已保存");setOpen(false);void load()}catch(e){if(axios.isAxiosError(e))message.error(err(e))}};
 const tree=(parentId=0):Org[]=>items.filter(item=>item.parentId===parentId).map(item=>({...item,children:tree(item.id)})).filter(item=>(status===undefined||item.status===status)&&(!keyword||item.name.toLowerCase().includes(keyword.toLowerCase())||item.code.toLowerCase().includes(keyword.toLowerCase())||!!item.children?.length));
 const downloadTemplate=()=>{const sheet=XLSX.utils.aoa_to_sheet([["组织名称","组织编码","上级组织编码","状态"],["示例清收公司","ORG-COLLECT","","正常"]]);sheet["!cols"]=[24,20,22,12].map(wch=>({wch}));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"组织机构");XLSX.writeFile(book,"组织机构导入模板.xlsx")};
 const importFile=async(file:File)=>{try{const book=XLSX.read(await file.arrayBuffer(),{type:"array"});const sheet=book.Sheets[book.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<(string|number)[]>(sheet,{header:1,raw:false,defval:""}).slice(1).map(row=>row.map(value=>String(value).trim())).filter(row=>row.some(Boolean));const organizations=rows.map(row=>({name:row[0],code:row[1],parentCode:row[2],status:["停用","0","否"].includes(row[3])?0:1}));if(!organizations.length){message.warning("导入文件没有有效数据");return}await axios.post("/api/basic-info/organizations/batch",{organizations});message.success(`成功导入 ${organizations.length} 个组织机构`);void load()}catch(e){message.error(err(e))}};
 const actionColumns=(canAdd||canEdit||canDelete)?[{title:"操作",width:260,render:(_:unknown,item:Org)=><Space>{canAdd&&<Button type="link" icon={<PlusOutlined/>} onClick={()=>openCreate(item.id)}>新增下级</Button>}{canEdit&&<Button type="link" icon={<EditOutlined/>} onClick={()=>{form.setFieldsValue(item);setOpen(true)}}>编辑</Button>}{canDelete&&<Popconfirm title="确认删除该组织？" onConfirm={async()=>{try{await axios.delete(`/api/basic-info/organizations/${item.id}`);message.success("已删除");void load()}catch(e){message.error(err(e))}}}><Button type="link" danger icon={<DeleteOutlined/>}>删除</Button></Popconfirm>}</Space>}] : [];
 return <section className="management-page">
  <Card size="small" className="query-card organization-query-card"><div className="organization-query-layout"><Space wrap><Input allowClear prefix={<SearchOutlined/>} placeholder="组织名称 / 组织编码" value={keyword} onChange={event=>setKeyword(event.target.value)} style={{width:260}}/><Select allowClear placeholder="组织状态" value={status} onChange={setStatus} style={{width:150}} options={[{value:1,label:"正常"},{value:0,label:"停用"}]}/>{canQuery&&<Button type="primary" icon={<SearchOutlined/>}>查询</Button>}<Button onClick={()=>{setKeyword("");setStatus(undefined)}}>重置</Button></Space><Space className="organization-query-actions"><Button icon={expanded.length?<ShrinkOutlined/>:<ArrowsAltOutlined/>} onClick={()=>setExpanded(expanded.length?[]:items.map(item=>item.id))}>{expanded.length?"全部收起":"全部展开"}</Button>{(canImport||canTemplate||canAdd)&&<><input ref={fileRef} hidden type="file" accept=".xls,.xlsx,.csv" onChange={event=>{const file=event.target.files?.[0];if(file)void importFile(file);event.target.value=""}}/>{canImport&&<Dropdown trigger={["hover"]} menu={{items:canTemplate?[{key:"template",label:"下载导入模板",icon:<DownloadOutlined/>}]:[],onClick:downloadTemplate}}><Button icon={<UploadOutlined/>} onClick={()=>fileRef.current?.click()}>批量导入</Button></Dropdown>}{!canImport&&canTemplate&&<Button icon={<DownloadOutlined/>} onClick={downloadTemplate}>下载导入模板</Button>}{canAdd&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>openCreate()}>新增组织</Button>}</>}</Space></div></Card>
  <DataGrid<Org> title="组织机构列表" preferenceKey="list-columns-organizations" rowKey="id" loading={loading} dataSource={tree()} pagination={false} expandable={{expandedRowKeys:expanded,onExpandedRowsChange:keys=>setExpanded(keys.map(Number))}} columns={[{title:"组织名称",dataIndex:"name",key:"name"},{title:"组织编码",dataIndex:"code",key:"code"},{title:"状态",dataIndex:"status",key:"status",render:value=><Tag color={value===1?"success":"default"}>{value===1?"正常":"停用"}</Tag>},...actionColumns]}/>
  <Drawer width={520} destroyOnHidden title={form.getFieldValue("id")?"编辑组织机构":"新增组织机构"} open={open} onClose={()=>setOpen(false)} extra={<Space><Button onClick={()=>setOpen(false)}>取消</Button><Button type="primary" onClick={()=>void save()}>保存</Button></Space>}><Form form={form} layout="vertical"><Form.Item name="id" hidden><Input/></Form.Item><Form.Item label="上级组织" name="parentId"><Select showSearch optionFilterProp="label" options={[{value:0,label:"顶级组织"},...items.filter(item=>item.id!==form.getFieldValue("id")).map(item=>({value:item.id,label:`${item.name} (${item.code})`}))]}/></Form.Item><Form.Item label="组织名称" name="name" rules={[{required:true,message:"请输入组织名称"}]}><Input/></Form.Item><Form.Item label="组织编码" name="code" rules={[{required:true,message:"请输入组织编码"}]}><Input placeholder="组织编码必须全局唯一"/></Form.Item><Form.Item label="状态" name="status"><Radio.Group options={[{label:"正常",value:1},{label:"停用",value:0}]}/></Form.Item></Form></Drawer>
 </section>;
}
