// @ts-nocheck -- china-area-data 的 JSON 静态类型无法表达运行时构造的递归 children 节点
import { useEffect, useState } from "react";
import axios from "axios";
import { Button, Cascader, Drawer, Form, Input, InputNumber, Popconfirm, Select, Space, Table, Tag, message } from "antd";
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from "@ant-design/icons";
import areaData from "china-area-data/data-array.json";
import { canAccess, useAuthStore } from "../../store/auth";
import { withDateColumnSorters } from "../../utils/tableSorters";
import { getErrorMessage } from "../../api/client";

type Kind="financeCompanies"|"financeProducts"|"collectionCompanies";
type Item={id:number;name:string;code:string;status:number;createdAt:string;companyId?:number;companyName?:string;contactName?:string;contactPhone?:string;address?:string;serviceArea?:string;productType?:string;annualRate?:number;termMonths?:number;remark?:string};
const meta={financeCompanies:{title:"金融公司管理",add:"新增金融公司",path:"finance-companies",key:"financeCompanies"},financeProducts:{title:"金融产品管理",add:"新增金融产品",path:"finance-products",key:"financeProducts"},collectionCompanies:{title:"清收公司管理",add:"新增清收公司",path:"collection-companies",key:"collectionCompanies"}} as const;
const errorText=(e:unknown)=>getErrorMessage(e);
const areaRows=areaData as Array<{name:string;value:string;parent?:string;children?:unknown[]}>;
const areaNodes=new Map(areaRows.map(row=>[row.value,row]));
const areaRoots=areaRows.filter(row=>{const parent=row.parent&&areaNodes.get(row.parent);if(!parent)return true;(parent.children??=[]).push(row);return false});
areaRows.splice(0,areaRows.length,...areaRoots);

export default function PartnerManagement({kind}:{kind:Kind}){
 const config=meta[kind],[form]=Form.useForm();
 const user=useAuthStore(state=>state.user),permissionBase=`basic:partner:${kind==="financeCompanies"?"finance-company":kind==="financeProducts"?"finance-product":"collection-company"}`;
 const canQuery=canAccess(user,`${permissionBase}:query`),canAdd=canAccess(user,`${permissionBase}:add`),canEdit=canAccess(user,`${permissionBase}:edit`),canDelete=canAccess(user,`${permissionBase}:delete`);
 const [items,setItems]=useState<Item[]>([]),[companies,setCompanies]=useState<Item[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[keyword,setKeyword]=useState(""),[status,setStatus]=useState<number>(),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[total,setTotal]=useState(0),[searchVersion,setSearchVersion]=useState(0);
 const load=async()=>{setLoading(true);try{const r=await axios.get(`/api/basic-info/${config.path}`,{params:{page,pageSize,keyword,status}});setItems(r.data[config.key]||[]);setTotal(r.data.total||0);if(kind==="financeProducts"){const c=await axios.get("/api/basic-info/finance-companies",{params:{page:1,pageSize:200}});setCompanies(c.data.financeCompanies||[])}}catch(e){message.error(errorText(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[kind,page,pageSize,searchVersion]);
 const edit=(item?:Item)=>{form.resetFields();form.setFieldsValue(item?{...item,serviceAreaPath:item.serviceArea?.split(" / ").filter(Boolean)}:{status:1,annualRate:0,termMonths:0});setOpen(true)};
 const save=async()=>{try{const value=await form.validateFields();if(kind==="collectionCompanies"){value.serviceArea=Array.isArray(value.serviceAreaPath)?value.serviceAreaPath.join(" / "):"";delete value.serviceAreaPath}value.id?await axios.put(`/api/basic-info/${config.path}/${value.id}`,value):await axios.post(`/api/basic-info/${config.path}`,value);message.success("保存成功");setOpen(false);void load()}catch(e){if(axios.isAxiosError(e))message.error(errorText(e))}};
 const remove=async(id:number)=>{try{await axios.delete(`/api/basic-info/${config.path}/${id}`);message.success("删除成功");void load()}catch(e){message.error(errorText(e))}};
 const detail:any[]=kind==="financeProducts"?[{title:"所属金融公司",dataIndex:"companyName",width:180},{title:"产品类型",dataIndex:"productType",width:130},{title:"年化利率",dataIndex:"annualRate",width:110,render:(v:number)=>`${v||0}%`},{title:"期限",dataIndex:"termMonths",width:100,render:(v:number)=>`${v||0} 个月`}]:kind==="collectionCompanies"?[{title:"联系人",dataIndex:"contactName",width:110},{title:"联系电话",dataIndex:"contactPhone",width:140},{title:"服务区域",dataIndex:"serviceArea",width:240},{title:"办公地址",dataIndex:"address",width:220}]:[{title:"联系人",dataIndex:"contactName",width:110},{title:"联系电话",dataIndex:"contactPhone",width:140},{title:"办公地址",dataIndex:"address",width:240}];
 const columns:any[]=withDateColumnSorters<Item>([{title:"名称",dataIndex:"name",fixed:"left",width:180},{title:"编码",dataIndex:"code",width:140},...detail,{title:"状态",dataIndex:"status",width:90,render:(v:number)=><Tag color={v===1?"success":"default"}>{v===1?"启用":"停用"}</Tag>},{title:"创建时间",dataIndex:"createdAt",width:170},...((canEdit||canDelete)?[{title:"操作",fixed:"right",width:150,render:(_:unknown,item:Item)=><Space>{canEdit&&<Button type="link" icon={<EditOutlined/>} onClick={()=>edit(item)}>编辑</Button>}{canDelete&&<Popconfirm title="确认删除该记录？" onConfirm={()=>void remove(item.id)}><Button type="link" danger icon={<DeleteOutlined/>}>删除</Button></Popconfirm>}</Space>}]:[])]);
 return <section className="management-page basic-info-page"><div className="query-card pro-query-card"><div className="query-form-row"><label><span>合作方检索</span><Input allowClear value={keyword} onChange={e=>setKeyword(e.target.value)} onPressEnter={()=>{if(canQuery){setPage(1);setSearchVersion(v=>v+1)}}} placeholder="名称 / 编码 / 联系人"/></label><label><span>状态</span><Select allowClear value={status} onChange={setStatus} placeholder="请选择状态" options={[{value:1,label:"启用"},{value:0,label:"停用"}]}/></label><div className="query-actions">{canQuery&&<Button type="primary" icon={<SearchOutlined/>} onClick={()=>{setPage(1);setSearchVersion(v=>v+1)}}>查询</Button>}<Button icon={<ReloadOutlined/>} onClick={()=>{setKeyword("");setStatus(undefined);setPage(1);setSearchVersion(v=>v+1)}}>重置</Button></div></div></div><div className="management-page-header list-page-header query-followup-actions"><Space className="list-header-actions">{canAdd&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit()}>{config.add}</Button>}</Space></div><Table className="pro-list-table" rowKey="id" loading={loading} dataSource={items} columns={columns} scroll={{x:"max-content"}} pagination={{current:page,pageSize,total,showSizeChanger:true,pageSizeOptions:["10","20","50","100"],showQuickJumper:true,showTotal:v=>`共 ${v} 条`,onChange:(next,size)=>{setPage(next);setPageSize(size)}}}/>
 <Drawer width="33%" title={form.getFieldValue("id")?`编辑${config.title.replace("管理","")}`:config.add} open={open} onClose={()=>setOpen(false)} extra={<Space><Button onClick={()=>setOpen(false)}>取消</Button><Button type="primary" onClick={()=>void save()}>保存</Button></Space>}><Form form={form} layout="vertical"><Form.Item name="id" hidden><Input/></Form.Item>{kind==="financeProducts"&&<Form.Item label="所属金融公司" name="companyId" rules={[{required:true,message:"请选择金融公司"}]}><Select showSearch optionFilterProp="label" options={companies.filter(v=>v.status===1).map(v=>({value:v.id,label:v.name}))}/></Form.Item>}<Form.Item label={kind==="financeProducts"?"产品名称":"公司名称"} name="name" rules={[{required:true,message:"请输入名称"}]}><Input/></Form.Item><Form.Item label={kind==="financeProducts"?"产品编码":"公司编码"} name="code" rules={[{required:true,message:"请输入编码"}]}><Input/></Form.Item>{kind==="financeProducts"?<><Form.Item label="产品类型" name="productType"><Select allowClear options={["车辆抵押贷","车辆融资租赁","消费信贷","其他"].map(value=>({value,label:value}))}/></Form.Item><Form.Item label="年化利率（%）" name="annualRate"><InputNumber min={0} max={100} precision={4} style={{width:"100%"}}/></Form.Item><Form.Item label="期限（月）" name="termMonths"><InputNumber min={0} precision={0} style={{width:"100%"}}/></Form.Item></>:<><Form.Item label="联系人" name="contactName"><Input/></Form.Item><Form.Item label="联系电话" name="contactPhone"><Input/></Form.Item>{kind==="collectionCompanies"&&<Form.Item label="服务区域" name="serviceAreaPath" extra="选填，可选择到省、市、区县"><Cascader allowClear changeOnSelect showSearch options={areaData} fieldNames={{label:"name",value:"name",children:"children"}} placeholder="请选择省 / 市 / 区县"/></Form.Item>}<Form.Item label="办公地址" name="address"><Input/></Form.Item></>}<Form.Item label="状态" name="status"><Select options={[{value:1,label:"启用"},{value:0,label:"停用"}]}/></Form.Item><Form.Item label="备注" name="remark"><Input.TextArea rows={4} maxLength={500} showCount/></Form.Item></Form></Drawer></section>
}
